### ISSUE TITLE
Attempted to read past the end of the stream. In Mysql 8 with buffer settings.

### ISSUE THREAD

**Issue by KamranShahid** [microknights/Log4NetAdoNetAppender#20]
I am using buffer for inserting the logs. I am having following error at the time of buffered.Flush

```
MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed.
 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MicroKnightsLogging.AdoNetAppender.SendBuffer(IDbTransaction dbTran, LoggingEvent[] events)
   at MicroKnightsLogging.AdoNetAppender.SendBuffer(LoggingEvent[] events)
   at log4net.Appender.BufferingAppenderSkeleton.SendFromBuffer(LoggingEvent firstLoggingEvent, CyclicBuffer buffer)
   at log4net.Appender.BufferingAppenderSkeleton.Flush(Boolean flushLossyBuffer)
   at log4net.Appender.BufferingAppenderSkeleton.Flush()
```

I am using .net core 3.1 with Mysql 8

**Comment by KamranShahid** [comment]
I am trying one possible workaround of using useTransactions = true which is currently set to false in my config

**Comment by microknights** [comment]
Can you send me your log4net configuration.

I am about to go through all issues and making a new release, so hopefully this one can be part of it - if required.

**Comment by KamranShahid** [comment]
[LoggingStuff.zip](https://github.com/microknights/Log4NetAdoNetAppender/files/4902044/LoggingStuff.zip)

If you see any other improvement then Please let me know.
Thanks

**Comment by microknights** [comment]
Hi @KamranShahid can you reproduce the problem with `MicroKnights.Log4NetAdoNetAppender 2.2.0-alpha2` ?

Cheers, Frank

**Comment by KamranShahid** [comment]
Sorry Frank bu i can try it in some days. busy in some other things

**Comment by microknights** [comment]
I am unable to reproduce the error you get, and in general the buffering is working. So if you need more investigating from my sight, please post a producible test either here, or even better include it in the UnitTest project. 

I have just release v2.2.0 so you can find the latest code in the master branch.

**Comment by KamranShahid** [comment]
Thanks Frank. About reproducing I got this in a RHEL instance of linux with Mysql 8. my project is a asp.net core 3.1 web api running there as a systemd service.
 I will try compare the updated code with the one which i have integrated in my project.

**Comment by KamranShahid** [comment]
Basically only change i see is  _lazyConnectionTypeResolve.
Can you give bit detail about what advantage we can get via this?

**Comment by KamranShahid** [comment]
My thinking is due to same command object utilization this error comes even we have usetransaction set false.

So i have created a logic to whether to use same command object or different for each insertion 
Please check SendBuffer method for my logic and suggest is this seems to be ok?

[MicroKnights.Logging.zip](https://github.com/microknights/Log4NetAdoNetAppender/files/5184599/MicroKnights.Logging.zip)

**Comment by KamranShahid** [comment]
May be it is also related to https://github.com/microknights/Log4NetAdoNetAppender/issues/28
So closing this issue
