### ISSUE TITLE
How can I create a custom column?

### ISSUE THREAD

**Issue by leojim06** [microknights/Log4NetAdoNetAppender#22]
I'm trying to create a custom column with the conversionPattern property and would like to know if this functionality is supported.
I'm saving logs of several applications and I want to save the name of the application, as well as an auto incremental number for each application
The way I am implementing it is as follows.

```XML
<?xml version="1.0" encoding="utf-8" ?>
<log4net debug="true">
	<root>
		<level value="ALL" />
		<appender-ref ref="ADONetAppender" />
	</root>
	<appender name="ADONetAppender" type="MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender">
		<bufferSize value="1" />
		<connectionType value="System.Data.SqlClient.SqlConnection,System.Data.SqlClient,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089" />
		<connectionString value="MyServerConnectionString" />
		<commandText value="insert into LogItem(LogItemNumber,LogItemDate,LogItemTimeStamp,LogItemThread,LogItemLevel,LogItemLogger,LogItemMessage,LogItemException) values (@logItemNumber,@logItemDate,@logItemTimeStamp,@logItemThread,@logItemLevel,@logItemLogger,@logItemMessage,@logItemException)" />
		<parameter>
                        <!--here my new column-->
			<parameterName value="@logItemNumber" />
			<dbType value="String" />
			<size value="255" />
			<layout type="log4net.Layout.PatternLayout">
				<conversionPattern value="%logCounter" />
				<converter>
					<name value="logCounter" />
					<type value="Utilities.LogCounterPatternConverter" />
				</converter>
			</layout>
                        <!--here my new column-->
		</parameter>
		<parameter>
			<parameterName value="@logItemDate" />
			<dbType value="DateTime" />
			<layout type="log4net.Layout.RawTimeStampLayout" />
		</parameter>
		<parameter>
			<parameterName value="@logItemTimeStamp" />
			<dbType value="Int64" />
			<layout type="log4net.Layout.PatternLayout">
				<conversionPattern value="%timestamp" />
			</layout>
		</parameter>
		<parameter>
			<parameterName value="@logItemThread" />
			<dbType value="String" />
			<size value="255" />
			<layout type="log4net.Layout.PatternLayout">
				<conversionPattern value="%thread" />
			</layout>
		</parameter>
		<parameter>
			<parameterName value="@logItemLevel" />
			<dbType value="String" />
			<size value="50" />
			<layout type="log4net.Layout.PatternLayout">
				<conversionPattern value="%level" />
			</layout>
		</parameter>
		<parameter>
			<parameterName value="@logItemLogger" />
			<dbType value="String" />
			<size value="255" />
			<layout type="log4net.Layout.PatternLayout">
				<conversionPattern value="%logger" />
			</layout>
		</parameter>
		<parameter>
			<parameterName value="@logItemMessage" />
			<dbType value="String" />
			<size value="8000" />
			<layout type="log4net.Layout.PatternLayout">
				<conversionPattern value="%message" />
			</layout>
		</parameter>
		<parameter>
			<parameterName value="@logItemException" />
			<dbType value="String" />
			<size value="8000" />
			<layout type="log4net.Layout.ExceptionLayout" />
		</parameter>
	</appender>
</log4net>
```

My pattern layout converter class is like this

```C#
namespace Utiities
{
    public sealed class LogCounterPatternConverter : PatternLayoutConverter
    {
        private static int LogCounter = 1;
        protected override void Convert(TextWriter writer, LoggingEvent loggingEvent)
        {
            writer.Write(LogCounter.ToString(CultureInfo.InvariantCulture));
            LogCounter++;
        }
    }
}
```

The error 

```CMD
log4net: Created Appender [RollingLogFileAppender]
log4net: Adding appender named [RollingLogFileAppender] to logger [root].
log4net: Loading Appender [ADONetAppender] type: [MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender]
log4net: Setting Property [BufferSize] to Int32 value [1]
log4net: Setting Property [ConnectionType] to String value [System.Data.SqlClient.SqlConnection,System.Data.SqlClient,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089]
log4net: Setting Property [ConnectionString] to String value [MyConnectionString]
log4net: Setting Property [CommandText] to String value [insert into LogItem(LogItemNumber,LogItemDate,LogItemTimeStamp,LogItemThread,LogItemLevel,LogItemLogger,LogItemMessage,LogItemException) values (@logItemNumber,@logItemDate,@logItemTimeStamp,@logItemThread,@logItemLevel,@logItemLogger,@logItemMessage,@logItemException)]
log4net: Setting Property [ParameterName] to String value [@logItemNumber]
log4net: Setting Property [DbType] to DbType value [String]
log4net: Setting Property [Size] to Int32 value [255]
log4net: Converter [message] Option [] Format [min=-1,max=2147483647,leftAlign=False]
log4net: Converter [newline] Option [] Format [min=-1,max=2147483647,leftAlign=False]
log4net: Setting Property [ConversionPattern] to String value [%logCounter]
log4net: Setting Property [Name] to String value [logCounter]
log4net:ERROR Could not create Appender [ADONetAppender] of type [MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender]. Reported error follows.
System.TypeLoadException: Could not load type 'NotificacionProgramadaWS.Utilidades.LogCounterPatternConverter' from assembly 'log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a'.
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at log4net.Util.SystemInfo.GetTypeFromString(Assembly relativeAssembly, String typeName, Boolean throwOnError, Boolean ignoreCase)
   at log4net.Util.TypeConverters.TypeConverter.ConvertFrom(Object source)
   at log4net.Util.OptionConverter.ConvertStringTo(Type target, String txt)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ConvertStringTo(Type type, String value)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.SetParameter(XmlElement element, Object target)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.CreateObjectFromXml(XmlElement element, Type defaultTargetType, Type typeConstraint)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.SetParameter(XmlElement element, Object target)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.CreateObjectFromXml(XmlElement element, Type defaultTargetType, Type typeConstraint)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.SetParameter(XmlElement element, Object target)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.CreateObjectFromXml(XmlElement element, Type defaultTargetType, Type typeConstraint)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.SetParameter(XmlElement element, Object target)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)
log4net:ERROR Appender named [ADONetAppender] not found.
log4net: Hierarchy Threshold []
```

The configuration is working fine as I have records in the database, but when I try to add the custom column I get the error

![imagen](https://user-images.githubusercontent.com/6011791/93729753-74fd3a80-fb8b-11ea-81bf-383a5da250e1.png)

**Comment by microknights** [comment]
I think you need to define the assembly as well in you type definition.

So
`<type value="Utilities.LogCounterPatternConverter" />`

must be something like
`<type value="Utilities.LogCounterPatternConverter, this-is-my-assembly-filename" />`

**Comment by microknights** [comment]
Beside that, wouldn't it be smarter to use a PrimaryKey with Auto Identity (1,1) (defined when creating the column on the sqlserver) for you `LogItemNumber` column? Else the number will restart from zero/0 every time you restart the application.
