### ISSUE TITLE
Error while opening SQL Connection (using .NET Core 3 Preview 6)

### ISSUE THREAD

**Issue by getangar** [microknights/Log4NetAdoNetAppender#8]
Hi,
first of all thanks for this package.

I would love to use this appender to log into the database in a .NET Core 3 Preview 6 application.
Unfortunately when the project starts and I initialise log4net, I get this error:

File name: 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at log4net.Util.SystemInfo.GetTypeFromString(Assembly relativeAssembly, String typeName, Boolean throwOnError, Boolean ignoreCase)
   at MicroKnights.Logging.AdoNetAppender.ResolveConnectionType()

I used the configuration file of example available here. Any Idea?

Thanks in advance!

**Comment by microknights** [comment]
I have never tested it with Core 3 Preview, but i dont think there are any breaking changes. Have you tries using matching preview of System.Data.SqlClient?

And what are the Exception message?

**Comment by getangar** [comment]
Hi there,
Thanks for the fast feedback.

I have tried with several mix of version (stable+preview) but regardless the version of the library I have in my project, the error is always the same. I tried both adding your Appender from NuGet or recompiling from the source code.

Btw, no exception, the behavior is that no logs are written in the database, but if you enable the debug mode of the Appender, then I get this in the output window of VS:

log4net:ERROR [AdoNetAppender] ErrorCode: GenericFailure. Failed to load connection type [System.Data.SqlClient.SqlConnection, System.Data, Version=1.0.3300.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview6-27804-01\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview6-27804-01\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview6-27804-01\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
File name: 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at log4net.Util.SystemInfo.GetTypeFromString(Assembly relativeAssembly, String typeName, Boolean throwOnError, Boolean ignoreCase)
   at MicroKnights.Logging.AdoNetAppender.ResolveConnectionType()


Thanks again!

**Comment by microknights** [comment]
Ok, thanks for the try out.

I will setup a Core 3 Preview environment, and see what happens on my machine ;)

Stay tuned.

**Comment by microknights** [comment]
Okay, here is the thing.

The problem is Type loading of the SqlClient, as the exception says. What fuzz me is that it should never had worked, but does until Core v3. So something must have been fixed.

The solution is easy, in your log4net.config replace:
`    <connectionType value="System.Data.SqlClient.SqlConnection,System.Data,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089" />`
with:
`    <connectionType value="System.Data.SqlClient.SqlConnection,System.Data.SqlClient,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089" />`

And give a status

**Comment by getangar** [comment]
Hi there, it seems to work :-)
Thanks and have a great day!
